# Generated by Django 3.0.3 on 2020-04-05 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Attikan Estate', max_length=200)),
                ('state', models.CharField(default='Kerala', max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'only alphabet')])),
                ('city', models.CharField(default='thiruvananthapuram', max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'only alphabet')])),
                ('altitude', models.IntegerField(default=450)),
                ('description', models.CharField(default='Bitter', max_length=700)),
                ('processing', models.CharField(default='fine grained', max_length=200)),
                ('characteristics', models.CharField(default='Little sweet', max_length=200)),
                ('img', models.ImageField(null=True, upload_to='gallery')),
                ('price', models.FloatField(default=340)),
            ],
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='gallery')),
                ('blend_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('acidic', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('sweet', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('salty', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('floral', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('chocolaty', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('nutty', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('bitter', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('savoury', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('spicy', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('berries', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('blend_batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidic', models.FloatField()),
                ('sweet', models.FloatField()),
                ('salty', models.FloatField()),
                ('floral', models.FloatField()),
                ('chocolaty', models.FloatField()),
                ('nutty', models.FloatField()),
                ('bitter', models.FloatField()),
                ('savoury', models.FloatField()),
                ('spicy', models.FloatField()),
                ('berries', models.FloatField()),
                ('blend_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Gen_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('blend_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('coffee', models.ManyToManyField(to='data.Blend')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='blend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Blend'),
        ),
    ]
