# Generated by Django 2.1.1 on 2018-10-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blend_Batch', models.IntegerField()),
                ('Img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BatchPicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='gallery')),
                ('Blend_Batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('altitude', models.IntegerField()),
                ('description', models.CharField(max_length=700)),
                ('processing', models.CharField(max_length=200)),
                ('characteristics', models.CharField(max_length=200)),
                ('img', models.ImageField(max_length=2000, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Gen_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('Blend_Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acidic', models.IntegerField()),
                ('Sweet', models.IntegerField()),
                ('Salty', models.IntegerField()),
                ('Floral', models.IntegerField()),
                ('Chocolaty', models.IntegerField()),
                ('Nutty', models.IntegerField()),
                ('Bitter', models.IntegerField()),
                ('Savoury', models.IntegerField()),
                ('Spicy', models.IntegerField()),
                ('Berries', models.IntegerField()),
                ('Blend_Batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=100)),
                ('Acidic', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Sweet', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Salty', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Floral', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Chocolaty', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Nutty', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Bitter', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Savoury', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Spicy', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('Berries', models.IntegerField(choices=[(0, '0-No'), (1, '1-Little bit'), (2, '2-Recognisable'), (3, '3-Moderate'), (4, '4-high'), (5, '5-Intense')], default=0)),
                ('blend_Batch_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(null=True, upload_to='')),
                ('Blend_Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='Blend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Blend'),
        ),
    ]
