# Generated by Django 3.0.5 on 2020-04-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Blend')),
            ],
        ),
        migrations.DeleteModel(
            name='CoffeeOrder',
        ),
    ]
