# Generated by Django 2.1.1 on 2018-10-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpicimage',
            name='Blend_Batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Blend_Batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Batch'),
        ),
    ]
