# Generated by Django 2.1.1 on 2018-10-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181010_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchPic',
        ),
        migrations.RemoveField(
            model_name='batchpicimage',
            name='Blend_Batch',
        ),
        migrations.AlterField(
            model_name='tasteprofile',
            name='Img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.DeleteModel(
            name='BatchPicImage',
        ),
    ]
