# Generated by Django 2.1.1 on 2018-10-24 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20181011_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'only alphabet')]),
        ),
        migrations.AlterField(
            model_name='blend',
            name='state',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z]*$', 'only alphabet')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Acidic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Berries',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Bitter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Chocolaty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Floral',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Nutty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Salty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Savoury',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Spicy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sweet',
            field=models.FloatField(),
        ),
    ]
