# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcase3checkout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcase3checkout(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(776, 741)
    self.driver.find_element(By.LINK_TEXT, "HOME").click()
    self.driver.find_element(By.LINK_TEXT, "COFFEE").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .img-responsive").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Checkout").click()
    dropdown = self.driver.find_element(By.ID, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'India']").click()
    element = self.driver.find_element(By.ID, "country")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "country")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "country")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "country").click()
    dropdown = self.driver.find_element(By.ID, "state")
    dropdown.find_element(By.XPATH, "//option[. = 'Maharashtra']").click()
    element = self.driver.find_element(By.ID, "state")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "state")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "state")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "state").click()
    self.driver.find_element(By.ID, "zip").click()
    self.driver.find_element(By.ID, "address").send_keys("Plot No 30, Ashtvinayak Society 2, Sr No: 289, D Y Patil College Road, Lohegaon,Pune, Maharashtra")
    self.driver.find_element(By.ID, "zip").send_keys("411047")
    self.driver.find_element(By.ID, "cc-name").click()
    self.driver.find_element(By.ID, "cc-name").send_keys("nkc")
    self.driver.find_element(By.ID, "cc-number").click()
    self.driver.find_element(By.ID, "cc-number").send_keys("459098789098")
    self.driver.find_element(By.ID, "cc-expiration").click()
    self.driver.find_element(By.ID, "cc-expiration").send_keys("10/12")
    self.driver.find_element(By.ID, "cc-cvv").send_keys("999")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
